### ISSUE TITLE
Problem in ggplot2 3.2.1

### ISSUE THREAD

**Issue by raonirosa** [zeehio/facetscales#11]
In this version of ggplot2, when I used:

ggplot (mydf, 
        aes (x = X, y = Y))+
  geom_boxplot()+
  facet_grid(Z ~., scales = list (y = scale_y))

Having scale_y a list with names of each facet painel (as in example code), I had this error message:

Error in match.arg(scales, c("fixed", "free_x", "free_y", "free")) : 
  'arg' must be NULL or a character vector

**Comment by zeehio** [comment]
Please use `facet_grid_sc` instead of `facet_grid` if you want to use the custom scales from `facetscales`.

**Comment by raonirosa** [comment]
Works perfectly, thanks!
