### ISSUE TITLE
Error in x$clone() : attempt to apply non-function

### ISSUE THREAD

**Issue by rsmth** [zeehio/facetscales#14]
I'm running into the error `Error in x$clone() : attempt to apply non-function`

Below is a reprex. The chart renders fine when I remove the `scales = list(y = scales_y, x = scales_x)` portion from `facet_grid_sc`

Any ideas?

```
df <- data.frame(
  name = rep(c('A', 'B', 'C'), 2),
  type = rep(c('type_1', 'type_2', 'type_1'), 2),
  metric = rep(c('metric_1', 'metric_2'), 3),
  value = c(.01, 90, .03, 80, .09, 50)
)

scales_y <- list(
  metric_1 = scale_y_continuous(labels = scales::percent_format()),
  metric_2 = scale_y_continuous(labels = scales::comma_format())
)

scales_x <- list(
  name = scale_x_discrete()
)

df %>%
  ggplot(aes(x = name, y = value, fill = type)) +
  facet_grid_sc(cols = vars(metric), scales = list(y = scales_y, x = scales_x)) +
  geom_bar(stat = 'identity')
```

**Comment by onurcanbektas** [comment]
I have the same issue as well

**Comment by gltyree** [comment]
I am also experiencing this issue.

**Comment by chris-s-bowden** [comment]
I have the same issue too

**Comment by kogurtsova** [comment]
The same by me. Would it be possible to fix it?

**Comment by zeehio** [comment]
I don't think maintaining this project is a good idea for reasons outlined in the readme. Therefore I am closing all issues and pull requests and archiving the project. Feel free to fork and maintain this if you like.

Apologies for not having responded earlier. It took me a while to decide that archiving was necessary.
