### ISSUE TITLE
Did not make change with coord_flip()

### ISSUE THREAD

**Issue by DrJerryTAO** [zeehio/facetscales#17]
Great contribution. But I want to report that your package did not work with `coord_flip()`. I found the problem when I created my own plot with horizontal bars (which is why I flipped the axes). The new (varying) axes text is missing except for the leftmost panel/facet. But when I removed `coord_flip() +`, your package worked perfectly. So it seems internally it worked, but the changes are not displayed. 

To reproduce the problem in your example data, you could try adding "`coord_flip() +`" to make the variable "Subject" on the y-axis, and renaming the subject names across different facet (e.g. A-D, a-d, 1-4, ID1-4, ...)

**Comment by zeehio** [comment]
I don't think maintaining this project is a good idea for reasons outlined in the readme. Therefore I am closing all issues and pull requests and archiving the project. Feel free to fork and maintain this if you like.

Apologies for not having responded earlier. It took me a while to decide that archiving was necessary.
