### ISSUE TITLE
help with geom_smooth and facet_grid_sc

### ISSUE THREAD

**Issue by pitla1** [zeehio/facetscales#18]
Dear Rxperts!

geom_smooth does not seem to work well when .combined with facet_grid_sc (... ,scales=list(x=scale_x, y=scale_y), ...)

```{r}
 
 tst <- data.frame(u = rep(1:10,each=10),a=rep(seq(10,100,len=10),10),p=runif(100)+10,q=runif(100)*10) %>% gather(.,,,3:4) %>% mutate(yvar="a")

ylbs <- c(a=bquote(monster~'@'~jupiter),b=bquote(monster~'@'~stars))
xlbs <- c(p=bquote(monster~'@'~moon),q=bquote(monster~'@'~mars))


scales_y1 = list(a = scale_y_continuous()); scales_x1=list(p="scale_x_log10()+annotation_logticks()",q="scale_x_log10()+annotation_logticks()")


ggplot(tst, aes(y=a,x=value))+geom_point() + facet_grid_sc(yvar~key,scales=list(y=scales_y1,x=list(eval(parse(text=scales_x1)))),labeller=labeller(key=as_labeller(xlbs,default=label_parsed),yvar=as_labeller(ylbs,default=label_parsed)),switch="both")+geom_smooth(method="loess",data=tst,col='red')+labs(x="",y="")+theme(strip.placement = "outside")
```

Any suggestions/ideas on to make geom_smooth and axis formats work with facet_grid_sc()...?
I do realize that there are other ways of doing it.. The reason is I am trying to generate a multipanel plot with customized x- & y- axis scales (one or more layers of formatting for one or more panels) and titles (may contain multi-line expressions)

Many thanks...

**Comment by teunbrand** [comment]
The `scales` argument in the `facet_grid_sc()` function is not the correct place to add annotations such as the logarithmic ticks.

The following runs fine for me, though I don't see an obvious need to declare two different x-axes that are the same:

``` r
library(tidyverse)
library(facetscales)

tst <- data.frame(u = rep(1:10,each=10),
                  a=rep(seq(10,100,len=10),10),
                  p=runif(100)+10,q=runif(100)*10) %>% 
  gather(.,,,3:4) %>% 
  mutate(yvar="a")

ylbs <- c(a=bquote(monster~'@'~jupiter),b=bquote(monster~'@'~stars))
xlbs <- c(p=bquote(monster~'@'~moon),q=bquote(monster~'@'~mars))


scales_y1 = list(a = scale_y_continuous())
scales_x1=list(p=scale_x_log10(),q=scale_x_log10())


ggplot(tst, aes(y=a,x=value))+
  geom_point() + 
  facet_grid_sc(yvar~key,
                scales=list(y=scales_y1, x= scales_x1), 
                labeller=labeller(key=as_labeller(xlbs,default=label_parsed),
                                  yvar=as_labeller(ylbs,default=label_parsed)),
                switch="both")+
  geom_smooth(method="loess",data=tst,col='red')+
  annotation_logticks(scaled = TRUE, sides = "b") +
  labs(x="",y="")+
  theme(strip.placement = "outside")
#> `geom_smooth()` using formula 'y ~ x'
```

![](https://i.imgur.com/UKfJ4OA.png)

<sup>Created on 2020-04-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by zeehio** [comment]
I don't think maintaining this project is a good idea for reasons outlined in the readme. Therefore I am closing all issues and pull requests and archiving the project. Feel free to fork and maintain this if you like.

Apologies for not having responded earlier. It took me a while to decide that archiving was necessary.
