### ISSUE TITLE
Does not load on mac

### ISSUE THREAD

**Issue by jakehosen** [zeehio/facetscales#2]
I'm running a mac (macos 10.13.5) with R 3.5.0. The install does not work correctly and in fact corrupts the existing installation of ggplot2. I had to uninstall facetscales and reinstall ggplot2 in order to get functionality restored.

I'm getting the following messages:

When I install:
> \*\* testing if installed package can be loaded
> \* DONE (facetscales)
> Warning message:
> In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1

So it says that it can load, but with a warning. However, when I go to load the library:
> library(facetscales)
> Error: package or namespace load failed for ‘facetscales’ in get(Info[i, 1], envir = env):
> lazy-load database '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/ggplot2/R/ggplot2.rdb' is corrupt
> In addition: Warning message:
> In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1

Let me know if I can help with this issue.

**Comment by zeehio** [comment]
That is weird. The only two times I have seen errors like this is when either there is a corrupted download  or when there are "invalid promises", due to package upgrades.

Have you tried to install `facetscales` from a new R session?

I'm going to set up travis CI, just to get better reproducibility. I'll try to set up a travis build on OSX as well to try to reproduce your issue. I'll be back once I have it running.

**Comment by zeehio** [comment]
I'm back. I could not reproduce your error on travis.

Could you try restarting your R session and trying again?

This issue happens from time to time with devtools and seems to be related to unfulfilled promises when unloading packages... 

The package does not do anything out of the ordinary anyway, so there is no apparent reason why it should fail on OSX...

I'll leave the issue open for a couple of days, feel free to close it if it is solved.

**Comment by jakehosen** [comment]
Hmm, so it installed fine with the new install of ggplot. Perhaps I unknowingly had an old version of ggplot. Working now, sorry to waste your time. Thanks for making this package.
