### ISSUE TITLE
Support multiple vars()

### ISSUE THREAD

**Issue by fabern** [zeehio/facetscales#21]
This seems to be a great package I have been searching for in a while.

I was wondering if it does support multiple variables in the same direction, e.g. `facet_grid_sc(rows = vars(drv, cyl))`, resulting in plots such as:
![Rplot01](https://user-images.githubusercontent.com/10245680/80766536-eccbb980-8b45-11ea-8ceb-db1abff0a73e.png)
Is this currently supported? What would be the format of the `scales = list(y= ...)` ?
Below I have tried my luck with a nested list. Unfortunately this doesn't work.

```
library(ggplot2)
library(facetscales)

data_to_plot <- mpg
data_to_plot$repeated_drv <- paste0("repeated_", data_to_plot$drv)

scales_y_multiple <- list(
  `4` = list(`repeated_4`= scale_y_continuous(limits = c(5, 25))),
  `f` = list(`repeated_f`= scale_y_continuous(limits = c(-40, 40))),
  `r` = list(`repeated_r`= scale_y_continuous(limits = c(10, 20))))

ggplot(data_to_plot, aes(displ, cty)) + 
  geom_point() + 
  facet_grid_sc(rows   = vars(drv, repeated_drv), 
                scales = scales_y_multiple) +
  theme_bw()
```

**Comment by zeehio** [comment]
No, multiple `vars()` are not supported. And I don't have much time to work on facetscales...

Pull requests are welcome though

**Comment by zeehio** [comment]
I don't think maintaining this project is a good idea for reasons outlined in the readme. Therefore I am closing all issues and pull requests and archiving the project. Feel free to fork and maintain this if you like.
