### ISSUE TITLE
facet_grid_sc() throws error with POSIXct on x-axis.

### ISSUE THREAD

**Issue by fabern** [zeehio/facetscales#22]
Using `facet_grid_sc()` together with a plot that uses `POSIXct` on x-axis throws an error: `Error: Invalid input: time_trans works with objects of class POSIXct only`

MWE:
```
library(lubridate)
library(dplyr)
library(ggplot2)
library(facetscales)

dat <- tribble(~dttm,                          ~value, ~group,
               ymd_hms("2020-04-05 11:00:00"), 10,     "A",
               ymd_hms("2020-04-05 12:00:00"), 15,     "A",
               ymd_hms("2020-04-05 11:00:00"), 2,      "B",
               ymd_hms("2020-04-05 12:00:00"), 6,      "B",
               ymd_hms("2020-04-05 11:00:00"), 100,    "C",
               ymd_hms("2020-04-05 12:00:00"), 150,    "C")

ggplot(dat, aes(x=dttm,y=value)) +
  geom_line() + geom_point() +
  facet_grid(rows = vars(group)) +
  theme_bw()

ggplot(dat, aes(x=dttm,y=value)) +
  geom_line() +
  facet_grid_sc(rows = vars(group)) +
  theme_bw()
```

**Comment by c1au6i0** [comment]
Yes same issue here

**Comment by zeehio** [comment]
Possibly fixed by https://github.com/zeehio/facetscales/pull/20 but I don't have time to test and fix this right now

**Comment by zeehio** [comment]
I don't think maintaining this project is a good idea for reasons outlined in the readme. Therefore I am closing all issues and pull requests and archiving the project. Feel free to fork and maintain this if you like.
