### ISSUE TITLE
Error when faceting by column

### ISSUE THREAD

**Issue by jgarces02** [zeehio/facetscales#24]
Hi @zeehio, thanks for attending so many requests for managing each facet independently, that's a very useful package!

My data looks like [that](https://pastebin.com/thCnhYfm) and faceting by row works nicely...
```
> data <- source("https://pastebin.com/raw/thCnhYfm")$value
> facetscales <- list(
  `col1` = scale_y_continuous(limits = c(0, 20), breaks = seq(0, 20, 5)),
  `col2` = scale_y_continuous(limits = c(0, 30), breaks = seq(0, 30, 5)),
  `col3` = scale_y_continuous(limits = c(0, 8), breaks = seq(0, 8, 2)),
  `col4` = scale_y_continuous(limits = c(0, 25), breaks = seq(0, 25, 5)))

> melt(data, id.vars = "group") %>% 
  ggplot(aes(group, value)) + geom_boxplot() +
  facetscales::facet_grid_sc(rows = vars(variable), scales = list(y = facetscales))
```
![image](https://user-images.githubusercontent.com/27858969/104906602-37b38880-5984-11eb-897e-7c8d8d3ce2b9.png)

... but if I want to facet by column, it brings me this error:
```
> melt(data, id.vars = "group") %>% 
  ggplot(aes(group, value)) + geom_boxplot() +
  facetscales::facet_grid_sc(cols = vars(variable), scales = list(y = facetscales))

Error in .subset2(x, i, exact = exact) : 
  attempt to select less than one element in get1index
In addition: Warning message:
In melt(data, id.vars = "group") :
  The melt generic in data.table has been passed a data.frame and will attempt to redirect to the relevant reshape2 method; please note that reshape2 is deprecated, and this redirection is now deprecated as well. To continue using melt methods from reshape2 while both libraries are attached, e.g. melt.list, you can prepend the namespace like reshape2::melt(data). In the next version, this warning will become an error.
```
Maybe I'm missing something. Could you help me, please? Thanks in advance.

**Comment by andisa01** [comment]
I am also getting this same error with my dataset when faceting column-wise, but not when I facet row-wise.

**Comment by zeehio** [comment]
I don't think maintaining this project is a good idea for reasons outlined in the readme. Therefore I am closing all issues and pull requests and archiving the project. Feel free to fork and maintain this if you like.

Apologies for not having responded earlier. It took me a while to decide that archiving was necessary.
