### ISSUE TITLE
Facet A, Facet B and others.

### ISSUE THREAD

**Issue by QihuangZhang** [zeehio/facetscales#25]
I have the problem that I have many facets and I just want to adjust the scale of y-axis for the first facet. Instead of specifying the parameter for each facet, I wonder if it possible to do

scales_y <- list(
  `A` = scale_y_continuous(limits = c(0.2, 0.8)),
  `**others**` = scale_y_continuous(limits = c(0, 40))
)

**Comment by zeehio** [comment]
It's not possible, but if you want to make a pull request with the feature I can review it

**Comment by zeehio** [comment]
I don't think maintaining this project is a good idea for reasons outlined in the readme. Therefore I am closing all issues and pull requests and archiving the project. Feel free to fork and maintain this if you like.
