### ISSUE TITLE
Boxplot looks different from facet_grid

### ISSUE THREAD

**Issue by mattocci27** [zeehio/facetscales#26]
Hi, I'm not sure why these two boxplots look different. In `facet_grid_sc`, y1
has shorter lines and doesn't have outliers.

```{r}
set.seed(123)
y1 <- rlnorm(200, 1, 4)
y2 <- rlnorm(200, 3, 5)

dat <- tibble(y1, y2) %>%
  pivot_longer(1:2) %>%
  mutate(gr = rep(c("gr1", "gr2"), each = 200))

ggplot(dat, aes(x = name, y = value)) +
  geom_boxplot() +
  facet_grid(gr ~ .) +
  scale_y_log10()
```
![unnamed-chunk-1-1](https://user-images.githubusercontent.com/12104199/110758414-7597a380-8287-11eb-97d6-dfd14036088d.png)

```{r}
scales_y <- list(
 gr1 = scale_y_log10(),
 gr2 = scale_y_log10())

ggplot(dat, aes(x = name, y = value)) +
  geom_boxplot() +
  facetscales::facet_grid_sc(rows = vars(gr),
                             scales = list(y = scales_y))
```
![unnamed-chunk-2-1](https://user-images.githubusercontent.com/12104199/110758443-7c261b00-8287-11eb-932e-6aca71c9f742.png)

**Comment by zeehio** [comment]
Wow that's a big bug!

To compute a boxplot, ggplot2 needs to do some statistics on the data (quartiles, outliers...) in order to draw the rectangles, lines and dots. From your example I see that all the facets in facetscales are identical which means that those statistics are probably computed on the whole dataset instead of on each facet.

I will put a big warning on the README for now. I hope to be able to fix this, otherwise I will have to retire the package.

**Comment by gatafornela** [comment]
I recently saw this [video](https://riffomonas.org/code_club/2021-05-28-log-scale) by [Pat Schloss](https://github.com/riffomonas) on the differences between using `scale_x_log10` or `coord_trans` when plotting data. I thought it may be relevant to this issue, as, apparently, `coord_trans` calculates the stats and then transform the axes, while `scale_y_log10` transforms the data and then calculates the statistics, altering the values of some stats, such as the mean (see also [this thread](https://stackoverflow.com/questions/38753628/ggplot-boxplot-length-of-whiskers-with-logarithmic-axis)). 

For whatever reason, it looks like `facetscales` resembles better the whiskers of the plots using `coord_trans` (the "correct" plot), even though the outliers are missing.

This does not explain why there is that difference between using `scale_y_log10` outside `facet_grid` or within `facet_grid_sc`, though, but perhaps it can provide some hints on how to solve the problem (if still a problem...).

```
library(tidyverse)
library(patchwork)

set.seed(123)
y1 <- rlnorm(200, 1, 4)
y2 <- rlnorm(200, 3, 5)

dat <- tibble(y1, y2) %>%
  pivot_longer(1:2) %>%
  mutate(gr = rep(c("gr1", "gr2"), each = 200))

# Original plot
a <- ggplot(dat, aes(x = name, y = value)) +
  geom_boxplot() +
  facet_grid(gr ~ .) +
  scale_y_log10(limits = c(1e-6,1e8),
                breaks = c(1e-3, 1e1, 1e+5)) + 
  labs(title="scale_y_log10")

# Using coord_trans
b <- ggplot(dat, aes(x = name, y = value)) +
  geom_boxplot() +
  facet_grid(gr ~ .) +
  coord_trans(y = "log10") + 
  scale_y_continuous(limits = c(1e-6,1e8),
                     breaks = c(1e-3, 1e1, 1e+5)) +
  labs(title="coord_trans")

# Using facetscales
scales_y <- list(
  gr1 = scale_y_log10(limits = c(1e-6,1e8),
                      breaks = c(1e-3, 1e1, 1e+5)),
  gr2 = scale_y_log10(limits = c(1e-6,1e8),
                      breaks = c(1e-3, 1e1, 1e+5)))

c <- ggplot(dat, aes(x = name, y = value)) +
  geom_boxplot() +
  facetscales::facet_grid_sc(rows = vars(gr),
                             scales = list(y = scales_y)) +
  labs(title="facetscales")

(a|b|c) & theme(panel.grid.minor.y = element_blank())
```
![imagen](https://user-images.githubusercontent.com/79043104/120072264-40833c00-c093-11eb-8beb-3c71bef519da.png)

**Comment by zeehio** [comment]
I don't think maintaining this project is a good idea for reasons outlined in the readme. Therefore I am closing all issues and pull requests and archiving the project. Feel free to fork and maintain this if you like.
