### ISSUE TITLE
facet_grid_sc cols argument not working

### ISSUE THREAD

**Issue by ojziff** [zeehio/facetscales#27]
In `facet_grid_sc` I get error when trying to plot the facet by columns using the cols argument:
```r
Error in .subset2(x, i, exact = exact) : 
  attempt to select less than one element in get1index
```
It works if i specify the `rows` argument. Likewise, if i use formula `type~.` it works but I get the same error above with `.~type`.

Would be best, if like facet_grid, we could specify nrow & ncol to have more control of the facet plotting.

Many thanks!

**Comment by zeehio** [comment]
I don't think maintaining this project is a good idea for reasons outlined in the readme. Therefore I am closing all issues and pull requests and archiving the project. Feel free to fork and maintain this if you like.
