### ISSUE TITLE
Unable to set variable scales of Y axis

### ISSUE THREAD

**Issue by Rashesh7** [zeehio/facetscales#5]
Hello,

Thank you for making this functionality. 
I am unable to set the Y axis scales while using facet_grid_sc. It just takes the values for the first category (limits=c(0,0.08)) for all. I am submitting the parameter as

scales_y <- list(
Category1" = scale_y_continuous(limits=c(0,0.08)), 
Category2 = scale_y_continuous(limits=c(0,0.22)), 
Category3 = scale_y_continuous(limits=c(0,0.08))
)
facet_grid_sc(Category ~ Sample,  scales=list(y = scales_y)) 

The full command is:
ggplot(data=melted,aes(x=variable,y=value,fill=majortype, width=0.4))+geom_bar(stat="identity") + scale_x_discrete(labels=melted$minortype) + theme( panel.grid.major = element_blank(), panel.grid.minor = element_blank(),  legend.title=element_blank(), legend.position="none", legend.text=element_text(size=0), axis.text.x=element_blank(), axis.text.y=element_text(angle = 90 , hjust = 0.5, size=5)) + guides(col = guide_legend(nrow = 1), fill =  guide_legend(nrow = 1)) + **facet_grid_sc(Category ~ Sample,  scales=list(y = scales_y))** + theme(plot.margin = unit(c(1.2,0.4,0.9,0.5), "lines"))

Am I incorrectly plotting this?

**Comment by ravenroadresources** [comment]
Hello, 
I have noticed that when faceting with multiple rows and columns, the ggproto function when defines facet_x_names and facet_y_names duplicate the names for each combination of rows * columns, causing the issues of repeating the parameters of the firsts scale.
Modify the lines in the `ggplot2::ggproto()` function adding `unique()` solve the issue:
`facet_x_names <- unique(as.character(layout[[names(params$cols)]]))` and 
`facet_y_names <- unique(as.character(layout[[names(params$rows)]]))`

**Comment by TheTS** [comment]
@ravenroadresources can you send in a pull request from your fork? It fixes this issue!

and @zeehio can you accept it :)

**Comment by zeehio** [comment]
I merged the patch! Thanks!
