### ISSUE TITLE
Does it support scale_y_log10?

### ISSUE THREAD

**Issue by ptoche** [zeehio/facetscales#6]
I'm new to both the package and ``scale_y_log10``, so I may be doing something very inapt. I was essentially trying to apply instructions for [annotation_logticks](https://ggplot2.tidyverse.org/reference/annotation_logticks.html) with the ``facetscales`` README example:

    mydf <- data.frame(
        Subject = rep(c("A", "B", "C", "D"), each = 3),
        Magnitude = rep(c("SomeValue", "Percent", "Scientific"), times = 4),
        Value = c(c(170,0.6,2.7E-4),
                c(180, 0.8, 2.5E-4),
                c(160, 0.71, 3.2E-4),
                c(159, 0.62, 3E-4)))

    scales_y <- list(
        Percent = scale_y_continuous(labels = percent_format()),
        SomeValue = scale_y_continuous(),
        logs = scale_y_log10(
            breaks = scales::trans_breaks("log10", function(x) 10^x),
            labels = scales::trans_format("log10", scales::math_format(10^.x))
        )
    )

    ggplot(mydf) +
        geom_point(aes(x = Subject, y = Value)) +
        facet_grid_sc(rows = vars(Magnitude), scales = list(y = scales_y))

and that gives 

    Error in x$clone() : attempt to apply non-function

What am I doing wrong? Thanks!

**Comment by ravenroadresources** [comment]
hello, 

the name of each item of the list defining the scales **must** correspond to the category used for faceting (Magnitude in this case). 
Either replace `"Scientific"` by `"logs"` when defining the data frame, or the other way round when you define scales_y.

**Comment by ptoche** [comment]
Why of course. Looks like I lost the plot. Thanks a lot. Here is fixed code:

    mydf <- data.frame(
        Subject = rep(c("A", "B", "C", "D"), each = 3),
        Magnitude = rep(c("SomeValue", "Percent", "Scientific"), times = 4),
        Value = c(c(170,0.6,2.7E-4),
                  c(180, 0.8, 2.5E-4),
                  c(160, 0.71, 3.2E-4),
                  c(159, 0.62, 3E-4)))

    library(ggplot2)
    library(facetscales)

    scales_y <- list(
        Percent = scale_y_continuous(labels = percent_format()),
        SomeValue = scale_y_continuous(),
        Scientific = scale_y_log10(
            breaks = scales::trans_breaks("log10", function(x) 10^x),
            labels = scales::trans_format("log10", scales::math_format(10^.x))
        )
    )

    ggplot(mydf) +
        geom_point(aes(x = Subject, y = Value)) +
        facet_grid_sc(rows = vars(Magnitude), scales = list(y = scales_y))

**Comment by ptoche** [comment]
Please close this issue. Thanks.

**Comment by zeehio** [comment]
Closing, thanks
